version: '3'

services:
    mysql:
        build:
            context: ./docker/mysql
        environment:
            MYSQL_DATABASE: "db"
            MYSQL_ROOT_PASSWORD: "root"
            MYSQL_USER: "admin"
            MYSQL_PASSWORD: "asdf1234"
        ports:
            - "3306:3306"
        volumes:
            - ./data-vol:/var/lib/mysql

    nginx:
        build:
            context: ./docker/nginx
        volumes:
            - ./src:/var/www
            - ./docker/nginx/conf.d/:/etc/nginx/conf.d
            - ./docker/nginx/sites-available/:/etc/nginx/sites-available
            - ./docker/nginx/nginx.conf:/etc/nginx/nginx.conf
        ports:
            - "80:80"
            - "443:443"
        depends_on:
            - php-fpm

    php-fpm:
        build:
            context: ./docker/php-fpm
        volumes:
            - ./src:/var/www
        depends_on:
            - mysql

